# Generated by Django 5.2.4 on 2025-08-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_group_groupexpense_groupmember_group_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupexpense',
            name='included_members',
            field=models.ManyToManyField(blank=True, related_name='included_in_expenses', to='project_app.registration'),
        ),
    ]
