# Generated by Django 5.1.7 on 2025-07-31 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_group_groupexpense_groupmember_group_members_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lending',
        ),
    ]
