# Generated by Django 5.2.4 on 2025-08-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0011_remove_groupexpense_included_members_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupExpense',
        ),
        migrations.DeleteModel(
            name='GroupExpenseSplit',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
