# Generated by Django 5.2.4 on 2025-08-09 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0013_group_groupexpense_groupmember_group_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'member')},
        ),
        migrations.AddField(
            model_name='groupexpense',
            name='included_members',
            field=models.ManyToManyField(related_name='included_expenses', to='project_app.registration'),
        ),
        migrations.AlterField(
            model_name='groupexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='groupexpense',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupexpense',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to='project_app.registration'),
        ),
        migrations.AlterField(
            model_name='groupexpensesplit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='role',
        ),
    ]
