# Generated by Django 5.2.4 on 2025-08-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0014_rename_user_groupmember_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
