# Generated by Django 5.1.7 on 2025-07-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
