# Generated by Django 5.2.4 on 2025-08-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0009_groupexpense_included_members'),
        ('project_app', '0009_remove_lending_model'),
    ]

    operations = [
    ]
