# Generated by Django 5.2.4 on 2025-08-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0010_merge_20250808_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupexpense',
            name='included_members',
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('trip', 'Trip'), ('home', 'Home'), ('friends', 'Friends'), ('work', 'Work'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
