# Generated by Django 5.1.7 on 2025-08-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0016_expense_created_by_expense_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='income',
            name='created_by',
        ),
    ]
