# Generated by Django 5.1.7 on 2025-10-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0017_remove_expense_created_by_remove_income_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
